version: '3.8'

services:
  # Service PHP avec Symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./var:/var/www/var
      - ./vendor:/var/www/vendor
    networks:
      - symfony

  # Serveur Nginx
  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - symfony

  # Base de données MySQL
  db:
    image: mysql:8
    container_name: symfony-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db_data:
