services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Service\UserService:
        arguments:
            $passwordHasher: '@security.password_hasher'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
